@AbapCatalog.viewEnhancementCategory: [#NONE]
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'Manage Data File FI'
@Metadata.ignorePropagatedAnnotations: true
@ObjectModel.usageType:{
    serviceQuality: #X,
    sizeCategory: #S,
    dataClass: #MIXED
}
define view entity ZJP_R_DATAFILE_FI
  as select from zup_data_file_fi
  association to parent ZJP_R_FILE_FI as _FileUpload on  $projection.UserUuid = _FileUpload.Uuid
                                                     and $projection.EndUser  = _FileUpload.EndUser
{
  key uuid                as Uuid,
      user_uuid           as UserUuid,
      end_user            as EndUser,
      doc_seq_no          as DocSeqNo,
      company_code        as CompanyCode,
      reference           as Reference,
      document_date       as DocumentDate,
      posting_date        as PostingDate,
      tax_det_date        as TaxDetDate,
      document_type       as DocumentType,
      doc_header_text     as DocHeaderText,
      currency            as Currency,
      translation_date    as TranslationDate,
      exchange_rate       as ExchangeRate,
      customer            as Customer,
      vendor              as Vendor,
      gl_account          as GlAccount,
      transaction_amount  as TransactionAmount,
      local_amount        as LocalAmount,
      payment_block       as PaymentBlock,
      baseline_date       as BaselineDate,
      cash_disc_base      as CashDiscBase,
      cash_disc_days1     as CashDiscDays1,
      cd_percent1         as CdPercent1,
      cash_disc_days2     as CashDiscDays2,
      cd_percent2         as CdPercent2,
      payment_method      as PaymentMethod,
      pmt_supplement      as PmtSupplement,
      payment_reference   as PaymentReference,
      partner_bank_type   as PartnerBankType,
      house_bank          as HouseBank,
      account_id          as AccountId,
      reason_code         as ReasonCode,
      net_pmt_term_period as NetPmtTermPeriod,
      recon_account       as ReconAccount,
      title               as Title,
      name1               as Name1,
      name2               as Name2,
      name3               as Name3,
      name4               as Name4,
      street              as Street,
      city                as City,
      postal_code         as PostalCode,
      country_region      as CountryRegion,
      region              as Region,
      email_address       as EmailAddress,
      bank_country        as BankCountry,
      bank_key            as BankKey,
      bank_account        as BankAccount,
      bank_control_key    as BankControlKey,
      tax_type            as TaxType,
      tax_number_type     as TaxNumberType,
      tax_number1         as TaxNumber1,
      tax_number2         as TaxNumber2,
      tax_number3         as TaxNumber3,
      tax_number4         as TaxNumber4,
      tax_number5         as TaxNumber5,
      natural_person      as NaturalPerson,
      item_text           as ItemText,
      tax_code            as TaxCode,
      tax_ctry_region     as TaxCtryRegion,
      assignment          as Assignment,
      ref_key1            as RefKey1,
      ref_key2            as RefKey2,
      ref_key3            as RefKey3,
      value_date          as ValueDate,
      cost_center         as CostCenter,
      profit_center       as ProfitCenter,
      order_no            as OrderNo,
      reason_code_2       as ReasonCode2,
      wbs_element         as WbsElement,
      functional_area     as FunctionalArea,
      tax_country         as TaxCountry,
      tax_amount          as TaxAmount,
      tax_base_tran_curr  as TaxBaseTranCurr,
      tax_amount_local    as TaxAmountLocal,
      tax_base_local      as TaxBaseLocal,
      tax_item_text       as TaxItemText,
      provider_contract   as ProviderContract,
      contract_item       as ContractItem,
      customer2           as Customer2,
      customer_group      as CustomerGroup,
      industry            as Industry,
      country_region_key  as CountryRegionKey,
      sales_org           as SalesOrg,
      dist_channel        as DistChannel,
      division            as Division,
      billing_type        as BillingType,
      @Semantics.user.createdBy: true
      createdbyuser as Createdbyuser,
      @Semantics.systemDateTime.createdAt: true
      createddate   as Createddate,
      @Semantics.user.lastChangedBy: true
      changedbyuser as Changedbyuser,
      @Semantics.systemDateTime.lastChangedAt: true
      changeddate   as Changeddate,
      //      _association_name // Make association public
      _FileUpload
}
